# this example uses service module in a playbook
- 
  # version 1
  name: Start some services
  hosts: localhost
  tasks:
    - name: Start the database service
      service: name=postgresql state=started

  # version 2
  name: Start some services
  hosts: localhost
  tasks:
    - name: Start the database service
      service:  
        name: postql
        start: started
      
    - name: Start the httpd service
      service: name=httpd state=started