# script runs task using with and loop using 'with_'
# examples include with_items, with_file:, with_url
-
  name: Create users
  hosts: localhost
  tasks:
    - user: name='{{ item }}}' state=present
    with_items:
      - joe
      - george
      - ravi
      - mani
      